=== Mission

We believe in total bodily autonomy - the right to do whatever you wish with your body. You don't have to "`be trans`" to transition, and transition does not have to mean following a fixed set of rules to make your body as close as possible to a cis one (although it can if you want it to!). We believe in informed consent - outlining the benefits and risks of every approach. When it comes to risk, this includes both the side-effects and the risks that only exist because of the state's attempts to control our bodies and our healthcare. We will provide information on approaches that we do not think are the best courses of action for _anyone_, because the best person to make decisions about your body is you.

Unfortunately, medical professionals do not always have your best interests at heart. Perhaps more often than this, many of them simply do not know enough. This might seem strange - after all, they _are_ supposed to be the experts. Their training, however (especially when it comes to GPs) is frequently insufficent, outdated or outright not present when it comes to treating trans patients. Thus the guidance here, especially around hormone dosage, will often disagree with what your doctor tells you. This guide is sourced, but telling your doctor they're wrong won't necessairily get them to give you the correct treatment. We believe that trans people can and should take their helthcare and their bodies into their own hands, and mould them how they see fit, with doctors only helping where they are actively wanted and not serving as the gatekeepers of care. That said, this guide will tell you how to transition through the NHS, if that is the route you want to go down. 