==== Estrogen

There are various ways to take estrogen. The availability of each of these differs depending on where you're getting your hormones from - see <<sourcing>> for more information. All however, have the same goal, of increasing your estradiol levels (and decreasing your testosterone levels), and all are the same chemical, just entering your body through different routes.

TIP: We would recommend injections or gel as the best routes if possible. If you have no choice but pills, we'd reccomend using the pills to produce stickies or taking sublingually or if this isn't possible taking sublingually. All these approaches mean the estrogen bypasses the liver, making for a safer _and_ more effective transition.

====== Summary

//TODO summary table

_For more information on each method, see below:_
.Injectables
[%collapsible]

=== 
Injectable estradiol comes in different forms, with each form releasing the estradiol into your body at a different rate.
===

.Gel
[%collapsible]

===

Estrogel is applied to the skin, and contains estradiol, an alchohol base to increase absorption and a thickener to provide a gel. It's generally applied to the skin once or twice a day. We'd recommend using estrogel in pump action bottles (like a soap dispenser) as this ensures consistent dosing - some <<DIY>> sources will provide estrogel in a tube which we would not recommend using as controlling dosages is harder. However, provided it is in a pump action bottle, homebrewed estrogel will be almost (sometimes entirely) identical to prescribed estrogen. 

Estrogel is available through the NHS, private care, the grey market, and homebrewers.
===
====== Patches

====== Solutions

====== Implants

====== Stickies

====== Pills

IMPORTANT: Do *NOT* attempt to use birth control pills to medically transition. These tend to contain Ethinylestradiol, which is not the same as the 17β estradiol that HRT contains. Whilst there may be some feminising effect from birth control pills, the amounts you would have to take to get your hormones to appropriate levels has a significant risk to your health. It's not hard to buy genuine HRT. Do that instead. Please. 


===== Dosing
