==== Estrogen

There are various ways to take estrogen. The availability of each of these differs depending on where you're getting your hormones from - see <<sourcing>> for more information. All however, have the same goal, of increasing your estradiol levels (and decreasing your testosterone levels), and all are the same chemical, just entering your body through different routes. They contain a bioidentical estrogen (ie exactly the same estradiol that your body produces, not merely a chemical that mimics its effects) - such as estradiol ethanate, estradiol hemihydrate or estradiol valerate (the ethanate/hemihydrate/valerate here is essentially a chemical that hold onto the estradiol and releases it into the body). 

TIP: We would recommend injections or gel as the best routes if possible. If you have no choice but pills, we'd reccomend using the pills to produce stickies or if this isn't possible taking sublingually. All these approaches mean the estrogen bypasses the liver, making for a safer _and_ more effective transition.

====== Summary

//TODO summary table

_For more information on each method, see below:_

.Injectables
[%collapsible]
==== 
Injectable estradiol comes in different forms, with each form releasing the estradiol into your body at a different rate - this rate is called a half-life. Shorter half lives require more frequent injections whereas longer half lives require slightly larger injections. The commonly available forms are:
- *Estradiol valerate (EV):* half-life ~3 days, inject every 5 days
- *Estradiol Cypionate (EC):* half-life ~7 days, inject every 7 days
- *Estradiol Enanthate's (EEn):* half-life ~5 days, inject every 7-10 days 

Injectables are not available on the NHS or private care in the UK, but are readily available both on the grey market and made by homebrewers.
====

.Gel
[%collapsible]
====
Estrogel is applied to the skin, and contains estradiol, an alchohol base to increase absorption and a thickener to provide a gel. It's generally applied to the skin once or twice a day. We'd recommend using estrogel in pump action bottles (like a soap dispenser) as this ensures consistent dosing - some <<DIY>> sources will provide estrogel in a tube which we would not recommend using as controlling dosages is harder. However, provided it is in a pump action bottle, homebrewed estrogel will be almost (sometimes entirely) identical to mass-manufactured estrogel.

Mass-manufactured estrogel is normally 0.06% estradiol and comes in 80g bottles. 

TIP: If switching between estrogel brands be sure to check the strength and pump size to ensure your dosage of estradiol remains the same.

Estrogel is available through the NHS, private care, the grey market, and homebrewers.
====

.Patches
[%collapsible]
====
Patches release a set level of estradiol per day. They're applied to either the buttock or lower stomach and need to be replaced once or twice a week. They may be available through the NHS, private care or the grey market.
====

.Solutions
[%collapsible]
====
Solutions consist of estradiol and an alchohol base to increase absorption. They are generally dropped onto the skin with an eyedropper, and are generally only available through homebrewers.
====


.Implants
[%collapsible]
====
Implants are pellets inserted into the fat layer beneath the skin that slowly release estrogen over 3-6 months. As these need to be inserted in a (very) minor surgery they're not available at all through homebrewers or the grey market, and access through private care or the NHS is almost impossible in the UK (offered, as of 2021, by one doctor in the whole country, and only then to people who have had their gonads removed already), but if they're really desired they can potentially be accessed through private care abroad.
====
//https://www.reddit.com/r/transgenderUK/comments/qt4ulv/estrogen_pellets_implant_uk/

.Stickies
[%collapsible]
====
The primary purpose of stickies is that they can be made incredibly easily from pills - the vase majority of people should be able to turn pills into stickies, but are released slower and directly into the bloodstream. This allows pills to be more cost effective (up to 10x cheaper from the same pills) and safer. They are placed in the mouth (pushed against a gum) and slowly release estradiol into the bloodstream, generally over a period of between 12-24 hours depending on thickness. This relies on not eating or drinking for an hour after applying them (application occurs once per day). Whilst stickies are only available through homebrewers (and we're not even aware of any homebrewers selling stickies, just individuals distributing to their networks), they can very easily be produced at home from pills (available from the NHS, private care, or the grey market) with normal household equipment.
====

====== Pills

IMPORTANT: Do *NOT* attempt to use birth control pills to medically transition. These tend to contain Ethinylestradiol (alongside a progestrin), which is not the same as the 17β estradiol that HRT contains. Whilst there may be some feminising effect from birth control pills, the amounts you would have to take to get your hormones to appropriate levels has a significant risk to your health. It's not hard to buy genuine HRT. Do that instead. Please. 

*Sublingual/buccal*

====== A note on non-bioidentical estrogens

Birth control pills tend to contain ethinylestradiol, which is an estrogen, just not _the_ estrogen you want. It's non-bioidentical, meaning that it merely mimics the effects of estrogen in the body. These have a signficantly increased blood clot risk compared to bioidentical estrogens. *Do not take them.* The only possible benefit from taking non-bioidentical applies only to people who had blocked some of their puberty - where the only measured effect is a small but statistically significant decrease in height (~2.1cm) when 100-200µg ethinylestradiol (significantly more than in a standard birth control pill but without progestrin) compared to standard estradiol treatment.

===== Dosing
