==== Sourcing

===== Homebrew

Homebrewed HRT is sometimes also referred to as bathtub estrogen - don't let this put you off. Homebrewing does not involve synthesising estrogen - homebrewers buy the same raw estrogen powder as is used to make commerical estrogen products - the homebrewing is just a process used to make this raw powder into something the body can actually take (such as injectables or gel). Some large scale homebrewers sell their hormones on the internet and ship across the coutry or the world - XXXX, but many homebrewing networks operate on a local scale of people producing usable estrogen for themselves and their community. These networks are crucial for many trans people, and we'd like to see them supported as fully as possible, and new networks forming is a good thing. To access these networks, we'd recommend hanging aroud with cool queer people. (seriously)

Estrogen is not a controlled substance but it is a prescription only medicine. If you are producing you are essentially running an unlicensed pharmacy but we are not aware of any examples of homebrewers facing legal consequences for producing and distributing feminising HRT. In the UK it is legal to buy or possess prescription only medicines (such as estrogen) without a prescription for personal use, or for others in your household. 

Homebrewing is not currently an option for blockers - but these can easily be sourced from the <<grey market>>. //TODO fix link

//TODO add examples of homebrewers

===== Recipies

*Stickies:* Stickies can be made very easily from estradiol pills. A full recipe https://stickies.neocities.org/stickies[is available here.] Stickies are used more widely than this guide suggests, and we know multiple people who have successfully used this recipe. They are safe and effective.

*Injectables:* producing both injectables and gel relies on buying raw estrogen powder from overseas (generally China). Test this if possible, or if this is not possible use trusted suppliers that others have tested. Below there is a list of tested suppliers. To test yourself XXXXXXX. The other ingredients and equipment for both can be bought on Amazon/eBay/Aliexpress/chemicals suppliers or possibly nicked from a lab if you have access to one of those. See below for instructions on how to make injectables on a small (batches of a few vials at a time, useful for yourself or a small group) or medium (batches of 20-50 vials at a time, useful for larger scale homebrew networks) scale.
//TODO explain how to test - both rough home tests and where to get commercial testing

Small Scale Production::
    * https://manufacturedbytyger.com/Tyger_Small_Guide.pdf[Recipe link]
    * https://web.archive.org/web/20230812121345/https://manufacturedbytyger.com/Tyger_Small_Guide.pdf[Archive link (if the above doesn't work)]
Medium Scale Production::
    * https://manufacturedbytyger.com/Tyger_Medium_Guide.pdf[Recipe link]
    * https://web.archive.org/web/20230812121350/https://manufacturedbytyger.com/Tyger_Medium_Guide.pdf[Archive link (if the above doesn't work)]
Tested Suppliers:: in progress
//TODO fill this in

*Gel:* gel reuires the same raws as injectables, see above for more info on this. Similarly to injectables, the other ingredients can be easily accquired. There are plenty of slightly different but similar recipes available online (many on https://www.reddit.com/r/estrogel/wiki/index/#wiki_d_-_generic_estradiol_gel_from_scratch[the r/estrogel wiki]) - try to ensure the result has actually been tested. The recipe below is adapted from https://www.reddit.com/r/estrogel/comments/zxc49u/estrogel_guide_looking_for_feedback/[this Reddit post,] and produces a product essentially identical to commercially available estrogel (although stronger) and has been successfully tested and shown to produce the expected changes in hormone levels. Many recipes available online include penetration enhancers - these help the skin to better absorb the estrogen and as such can increase the absorption of estrogen through the skin meaning that a lower dose is needed for the same result. Whilst the recipe below doesn't include them, that's not a stance against them, they can be useful for some people (although some can make the gel slightly irritant). If access to pharmaceutical ingredients other than estradiol is a difficulty, estrogel can also be produced from raw powder mixed with hand sanitiser. This is referred to as plan A, and a very basic recipe is 0.12g estradiol disolved in ethanol if possible and then mixed with 100ml of hand sanitiser, but more recipies are available elsewhere, including the aforementioned wiki.

.Recipe
[%collapsible%open]
====
****

The measurements below produce 100ml of 0.2% gel (this means that there are 2mg of estradiol in 1g of gel approximately 3x the strength of commercially available estrogel) - to increase or decrease the final product volume, change all measurements proportionally.

IMPORTANT: Gel requires the use of raw 17β-estradiol (Cas 50-28-2) as opposed to an ester such as estradiol valerate. This is because these esters don't absorb through the skin well.

TIP: If you don't have access to 63% Isopropyl alcohol (you probably won't) it can be made by mixing stronger Isopropyl (eg 70%, 99.9%) with distilled water such that the overall concentration is 63%. The amount of water to use can be found with https://www.omnicalculator.com/food/alcohol-dilution[this calculator]. Distilled water can be bought but https://www.wikihow.com/Make-Distilled-Water[can also be produced in the home.] Using boiled tap water will also produce water that is safe to use, but depending on impurities in the water there is a risk that it will intefere with the gel and may reduce the shelf life.

//TODO explain why we make stronger gel
//TODO explain differnce between grams and ml
//todo explain pump bottles are dead expensive - where cheap/alternatives etc
//todo do calcs for 70% and 99.9%
*Ingredients:*

* 17β-estradiol - 0.20g

* 63% Isopropyl alcohol - 99ml

* Carbomer 940 - 0.50g

* Triethanolamine - 0.75g


*Equipment:*

* 200ml beaker

* Digital scale with 0.001g resolution

* Small containers for weighing solids

* 200ml syringe to fill bottles

* 4x100ml airless pump bottles

* (Optional) milk frother for mixing

*Method:*

. Measure alcohol and add to beaker

. Add estradiol, mix util fully dissolved

. Add carbomer, small amounts at a time, mixing throughout. Mix until smooth. _Expect this to take a while (maybe 30 mins)_

. Add water if necessary (see above for more info)

. Cap syringe and pour mixture in

. Add triethanolamine to syringe and mix - should thicken rapidly

. Squeeze mixture into bottle and put cap on bottle

. Pump bottle until air stops coming out

****
====

===== NHS

//TODO note guidelines about BMI <40

The "official" recommended route for getting hormones in the UK is through a <<GIC>> - the main route to accessing trans healthcare for free (or nearly free - outside of Scotland prescriptions aren't usually free). A full guide to accessing GICs can be found here (_in progress_). GPs can (and should) also offer you briding prescriptions if you have been reffered (by them) to a GIC and you are accessing DIY HRT. A bridging prescription is your GP prescribing you HRT as opposed to the GIC prescribing to you. Just because they should doesn't mean they will, and in our experience the majority of GPs will not give you a briding prescription (but some of them will). There are lists out there (_in progress_) of GP practices that are more likely to prescribe.

//TODO write full thing about accsessing nhs care
//TODO find and link lists

===== Private

Private prescribers such as GenderGP and GenderCare are private clinics that provide trans healthcare. They are far more expensive than the NHS for long term use, but can often be used to obtain a shared care agreement with your GP, whereby the NHS provides blood tests and prescriptions whilst the private provider provides appointments. Like bridging prescriptions, not all GPs will provide shared care, although more offer shared care than do bridging prescriptions. If going down this route we'd recommend GenderCare, London Transgender Clinic or Harley Street Transgender Clinic, *not GenderGP - since it is generally harder to get shared care agreements through them.* It is difficult to switch between private providers, so if you think you can't afford the ongoing fees and private prescriptions, avoid GenderGP. If you can afford this however, GenderGP is less gatekeepy than other providers as they operate on more of an informed consent model so you may get hormones faster and through a slighly kinder process. For a more in depth guide see - _work in progress_

//TODO full guide on private care

===== Grey Market

Grey market drugs are produced in countries with looser pharmaceutical regulations such as India and China and sold over the counter there. These regulations don't make the drugs less safe, just mean that pharmacies can sell them to people without a prescription. When legitimate, they are exactly the same thing you'd get prescribed in the UK - often the only difference is which language the leaflet is written in. There are various online stores which these can be bought from. https://hrt.coffee/[hrt.coffee] maintains a list of trusted suppliers (note that it includes a few homebrewers such as otokonoko) selling estrogen, blockers, SERMs, finasteride and dutasteride.