name: 'Build site'

on: [push]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    steps: 
      
      - uses: actions/checkout@v3
      
      - name: Initialise
        run: echo Building Site
      
      - name: Install
        run: |
          sudo gem install asciidoctor-pdf
          sudo apt install -y asciidoctor
        
      - name: Build pdf
        run: asciidoctor src/index.adoc -o pdf/out.pdf -b pdf -r asciidoctor-pdf
      
      - name: Build html
        run: asciidoctor src/index.adoc -o index.html
      
      - name: Push changes
        run: |
          git config --global user.name 'Trans-Healthcare-UK'
          git config --global user.email 'trans-healthcare-uk@users.noreply.github.com'
          git add .
          git commit -m "generated"
          git push
      
